services:
  doc-sorter:
    build: .
    container_name: smart-doc-sorter
    ports:
      - "8080:8080"
    environment:
      - APP_STORAGE_STAGING_DIR=/app/storage/staging
      - APP_STORAGE_TARGET_DIR=/app/storage/target
      # Direct routing to your Windows Server machine
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - /Volume2/homes/${USER_DIR}/docker/smart-doc-sorter/staging:/app/storage/staging
      - /Volume2/homes/${USER_DIR}:/app/storage/target
    user: "0:0"
    restart: unless-stopped